hive:
  ##############需要打一个Docker Image，IP需要传进来##############
  url: jdbc:hive2://10.75.115.49:10000/default
  #url: jdbc:hive2://10.15.171.60:10000/ca4mndino
  #url: jdbc:hive2://10.75.141.216:10000/ca4mneiffel
  driver-class-name: org.apache.hive.jdbc.HiveDriver
  
  type: com.alibaba.druid.pool.DruidDataSource
  #type: org.apache.tomcat.jdbc.pool.DataSource
  
  user: hive
  password: ~
  # 下面为连接池的补充设置，应用到上面所有数据源中
  # 初始化大小，最小，最大
  initialSize: 1
  minIdle: 3
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 300000
  validationQuery: select 1
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
